site_name: WhyHow API
nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorial: tutorial.md
  - API Documentation: api.md

theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.code.copy
    - search.suggest
    - search.highlight
    - toc.follow

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_heading: true

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
